name: Selenium TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Check Chrome version
        run: google-chrome --version && chromedriver --version

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: Run TestNG Selenium Tests
        run: |
          echo "Running Selenium tests..."
          mvn -B test -Dsurefire.useFile=false
